version: 2.1

jobs:
  run_tests:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            sudo npm install -g
      - run:
          name: Run Tests
          command: |
            jest --ci --runInBand --reporters=default --reporters='jest-html-reporters'
 

workflows:
  build_test:
    jobs:
      - run_tests
