version: 2.1

jobs:
  run_tests:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            sudo npm install -g
      - run:
          name: Install Jest Reporter
          command: |
            sudo npm install jest-html-reporters
      - run:
          name: Run Tests
          command: |              
              sudo npm test --ci --runInBand 
          environment:
              JEST_HTML_REPORTER_OUTPUT_PATH: ~/report/
      - store_artifacts:
          path: ~/report/
      - store_test_results:
          path: ~/report/
 

workflows:
  build_test:
    jobs:
      - run_tests
