version: 2.1

jobs:
  run_tests:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            sudo npm install -g
      - run:
          name: Install Jest Reporter
          command: |
            npm install jest-html-reporters
      - run:
          name: Run Tests
          command: |
              mkdir -p ~/test-results/reporter
              npm test --ci --reporters=jest-html-reporters
 

workflows:
  build_test:
    jobs:
      - run_tests
