version: 2.1

jobs:
  run_tests:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            sudo npm install -g
      - run:
          name: Run Tests
          command: |
            ./node_modules/jest/bin/jest -i test/*.js -t --reporters='default' --reporters='jest-html-reporters'
          - store_test_results:
            path: ./reports/jest/
          - store_artifacts:
            path: ./reports/jest  

workflows:
  build_test:
    jobs:
      - run_tests